### ISSUE TITLE
Question: Is it possible to link nodes/edges?

### ISSUE THREAD

**Issue by cknoll** [twosigma/nxv#1]
I use nxv to create svg-files. In general svg-files can contain links or even js-code. I want to create kind of a feedback mechanism for nxv-generated graphs: every node and every edge should be "clickable" and trigger a modal dialog with a feedback form specific to that element. A first step would be to wrap the node and edge elenents in `<a>`-tags. Is this possible e.g. with custom styles?

See also https://stackoverflow.com/questions/66263255/how-to-make-an-svg-interactive-to-gather-comments-annotations-on-depicted-elemen

**Comment by timothy-shields** [comment]
See https://www.graphviz.org/doc/info/attrs.html#d:id

You can use this GraphViz attribute to provide unique IDs for the elements in your output SVG. Then once you have mounted the SVG into your DOM, you can use document.getElementById(id) to get references to and register event handlers on the mounted SVG elements.

**Comment by cknoll** [comment]
Sounds interesting. I will try it soon.

**Comment by cknoll** [comment]
I tried for a while but could not figure out how or where to specify the custom id on the python side.

I tried to add `node.id= next_id()` (for every node of the networkx-graph)  and  to pass some `"id": next_id()`-pair inside the node-style-lambda-dict of `nxv.Style(...)`.

Additionally: [this line](https://github.com/twosigma/nxv/blob/170bb6cb64478611f77dace367759c84b44b76b4/src/nxv/_rendering.py#L114) seems to indicate that the node-format is hardcoded somehow(?).

For reference, this is my current code: <https://nbviewer.jupyter.org/github/cknoll/semantictools/blob/main/doc/demo_notebooks/bfo_visualization.ipynb>.

**Comment by timothy-shields** [comment]
The `Style` parameters can be functions that map the parts of a graph to different styles. For example:

```
import networkx as nx
import nxv

graph = nx.Graph()
graph.add_edge("A", "B")
style = nxv.Style(
    node=lambda u, d: {
        "id": f"node_{u}",
        "label": u,
    }
)
svg = nxv.render(graph, style, format="svg")
```

This will generate an SVG where the XML elements for the two nodes will have the attributes `id="node_A"` and `id="node_B"` respectively.

**Comment by cknoll** [comment]
I thought, I already tried that – but apparently I did something wrong. This works as expected! Thanks!

**Comment by timothy-shields** [comment]
Were you able to get everything working the way you wanted to?

**Comment by cknoll** [comment]
Yes. Thank you again!
